"""Generate docs/TOOLS.md from the published MCP tool schemas.

The published ``tools/list`` schemas are the source of truth: the same
input/output shapes clients see on the wire. ``tests/test_tool_reference_sync.py``
fails when the committed file drifts from them.

Usage:
  python scripts/generate_tool_reference.py          # write docs/TOOLS.md
  python scripts/generate_tool_reference.py --check  # exit 1 on drift
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "TOOLS.md"

HEADER = """\
<!-- Generated by scripts/generate_tool_reference.py; do not edit by hand. -->

# MCP tool reference

Generated from the published `tools/list` schemas of the full MCP profile.
Each tool publishes an output schema shaped as `anyOf[success, error]`: the
tables below describe the success arm, and tool execution failures carry
`{"error": "..."}` under `isError: true` (see [MCP_GUIDE.md](MCP_GUIDE.md)).

Regenerate after changing tool signatures or contracts:

```bash
python scripts/generate_tool_reference.py
```
"""


def _escape_cell(value: object) -> str:
    text = " ".join(str(value).split())
    return text.replace("|", "\\|")


def _format_type(spec: dict[str, Any], defs: dict[str, Any]) -> str:
    if "$ref" in spec:
        return spec["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in spec:
        return " | ".join(_format_type(part, defs) for part in spec["anyOf"])
    if "enum" in spec:
        return "enum(" + ", ".join(repr(v) for v in spec["enum"]) + ")"
    kind = spec.get("type")
    if kind == "array":
        return f"{_format_type(spec.get('items', {}), defs)}[]"
    if kind == "object":
        extra = spec.get("additionalProperties")
        if isinstance(extra, dict) and extra:
            return f"record<string, {_format_type(extra, defs)}>"
        if spec.get("properties"):
            return "object"
        return "object"
    if kind == "null":
        return "null"
    if kind is None and "const" in spec:
        return repr(spec["const"])
    return str(kind)


def _success_arm(schema: dict[str, Any]) -> dict[str, Any]:
    arms = schema.get("anyOf")
    if isinstance(arms, list) and arms:
        return arms[0]
    return schema


def _render_tool(tool: Any) -> str:
    schema = tool.output_schema or {}
    success = _success_arm(schema)
    defs = schema.get("$defs") or {}
    lines: list[str] = [f"## {tool.name}", "", tool.description or "", ""]

    input_schema = tool.input_schema or {}
    properties = input_schema.get("properties") or {}
    required = set(input_schema.get("required") or [])
    lines += ["### Input", ""]
    if not properties:
        lines += ["Takes no arguments.", ""]
    else:
        lines += [
            "| Parameter | Type | Required | Default | Description |",
            "| --- | --- | --- | --- | --- |",
        ]
        for name, spec in properties.items():
            type_text = _format_type(spec, defs).replace("|", "\\|")
            if "default" not in spec:
                default_repr = "—"
            else:
                default = spec["default"]
                if default is None:
                    default_repr = "`null`"
                elif isinstance(default, bool):
                    default_repr = f"`{str(default).lower()}`"
                elif isinstance(default, str):
                    default_repr = f"`{default!r}`"
                else:
                    default_repr = f"`{default}`"
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{name}`",
                        f"`{type_text}`",
                        "yes" if name in required else "no",
                        default_repr,
                        _escape_cell(spec.get("description", "")),
                    ]
                )
                + " |"
            )
        lines.append("")

    out_properties = success.get("properties") or {}
    out_required = set(success.get("required") or [])
    lines += ["### Output", ""]
    if not out_properties:
        lines += ["Free-form object (no declared fields).", ""]
    else:
        lines += [
            "| Field | Type | Required | Description |",
            "| --- | --- | --- | --- |",
        ]
        for name, spec in out_properties.items():
            type_text = _format_type(spec, defs).replace("|", "\\|")
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{name}`",
                        f"`{type_text}`",
                        "yes" if name in out_required else "no",
                        _escape_cell(spec.get("description", "")),
                    ]
                )
                + " |"
            )
        lines.append("")
    return "\n".join(lines)


def render() -> str:
    from consolidation_memory import server

    tools = asyncio.run(server.mcp.list_tools())
    body = "\n".join(_render_tool(tool) for tool in tools)
    toc = "\n".join(f"- [{tool.name}](#{tool.name})" for tool in tools)
    return f"{HEADER}\n## Tools\n\n{toc}\n\n{body}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if docs/TOOLS.md is stale")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print("docs/TOOLS.md is stale; run scripts/generate_tool_reference.py", file=sys.stderr)
            return 1
        print("docs/TOOLS.md is up to date")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
